services:
  skgm:
    image: meseta/skgm:v1.1.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
      - "5000:5000"
    volumes:
      - skgm-data:/home/skgm/.config/skgm

volumes:
  skgm-data: